In [199]:
import torch
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=torch.tensor([1.1,2.0,3.0],requires_grad=True)
z=y
z

tensor([1.1000, 2.0000, 3.0000], requires_grad=True)

In [201]:
import torch.autograd as gradient
a_1=gradient.grad(z,inputs=y,grad_outputs=torch.ones_like(x),create_graph=True)[0]

In [202]:
a_1

tensor([1., 1., 1.])

In [203]:
out=torch.ones_like(x)
x

tensor([1., 2., 3.], requires_grad=True)

In [204]:
a2=gradient.grad(a_1,inputs=y,grad_outputs=out)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [196]:
aa

(tensor([2., 2., 2.]),)

In [197]:
aaa=gradient.grad(aa,inputs=y,grad_outputs=out,create_graph=True)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [198]:
aaa

(tensor([0., 0., 0.]),)